### ISSUE TITLE
reorg module hierarchy so bp_core includes network routers.

### ISSUE THREAD

**Issue by tommydcjung** [black-parrot/pre-alpha-release#123]

**Comment by dpetrisko** [comment]
Which routers is this referring to?

**Comment by tommydcjung** [comment]
talking about the routers inside the me networks.

**Comment by dpetrisko** [comment]
What’s the motivation to move them to core?

**Comment by tommydcjung** [comment]
we want to have BE+FE+CCE+routers as one hierarchy node in physical design, so we can stamp them out in tiled fashion. Just like we include router in manycore tile.

**Comment by dpetrisko** [comment]
But that’s bp_top. What is in ME in this organization?

**Comment by taylor-bsg** [comment]
bp_top can instantiate bp_tile; the network links will be the main
interface for bp_tile.

**Comment by dpetrisko** [comment]
Wait, what’s bp_tile now?

**Comment by taylor-bsg** [comment]
The replicated unit of the multicore; contains 1 CCE, 2 routers, 1 FE, 1 BE.

**Comment by dpetrisko** [comment]
So bp_core becomes bp_tile? Or bp_tile instantiates bp_core and bp_me_top?

**Comment by taylor-bsg** [comment]
bp_tile could instantiate two routers, one bp_core, and one CCE.
