### ISSUE TITLE
Committed binary files

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/pre-alpha-release#128]
There were some committed and deleted binary files in branch be_dev_vm_tests.  We don't want these to end up in our git history, so  we need to rewrite the history of this branch.  I'll close this issue once those binaries are gone from the history.

**Comment by iihihiuh** [comment]
Just updated. Please, see if this work.

**Comment by dpetrisko** [comment]
Hm, it seems a little strange, there are like 250,000 changed lines.  It kind of looks like this commit is totally dissociated with the previous history

**Comment by iihihiuh** [comment]
I created another branch "be_dev_vm_test" that spin off from be_dev. History record seems good to me. Branch "be_dev_vm_tests" is removed.

**Comment by dpetrisko** [comment]
Okay cool, history looks good. What is test.S.main.S?  It's really big, is it the output of running some script? If so, we should just commit the script

**Comment by iihihiuh** [comment]
Are we allowed to add an empty folder in the repository?

**Comment by dpetrisko** [comment]
No, git does not allow you to do so.  Why do you need one?

**Comment by iihihiuh** [comment]
Actually, I do not need it. Thanks. Everything should be fine by now.
