### ISSUE TITLE
limit the number of outstanding uncached store requests.

### ISSUE THREAD

**Issue by tommydcjung** [black-parrot/pre-alpha-release#131]

**Comment by taylor-bsg** [comment]
Also related to this; since this is likely to be implemented with a credit counter:

Implement fence instruction that allows us to confirm that we have no outstanding credits.

M

**Comment by tommydcjung** [comment]
The problem is that once uncached store is sent out, there is no ack coming back to LCE to restore the credit.

**Comment by dpetrisko** [comment]
If there’s some guaranteed latency by which you’re guaranteed to have completed, you could increment based on that?

**Comment by tommydcjung** [comment]
maybe. uncached store will raise miss, if the network was busy, and it will have to be replayed and retry. what if we increase the delay between each retry by some increasing function?

**Comment by tommydcjung** [comment]
but that still doesn't solve the problem with not knowing when to restore the credit..

**Comment by dpetrisko** [comment]
I'm saying you can restore the credit when a cycle counter exceeds the maximum latency

**Comment by black-parrot** [comment]
All stores should have an acknowledgement packet, and there should be a counter that counts them.  There is no deterministic number of cycles after which we know a store has completed in the I/O system. Since loads have a response packet, there must be a pathway to implement a store ack packet.

**Comment by dpetrisko** [comment]
That works, too

**Comment by taylor-bsg** [comment]
It will give you a reason to implement fence, .rl and .aq. ;-)

**Comment by dpetrisko** [comment]
Added in be_dev 548b0b6
