### ISSUE TITLE
Investigate Midas (Strober)

### ISSUE THREAD

**Issue by dpetrisko** [black-parrot/pre-alpha-release#139]
https://github.com/ucb-bar/midas/blob/90b2bd76e05bd26294cedb2f5f4e40c8c1e6bded/README.md

> MIDAS is a Chisel & FIRRTL library for generating FPGA-accelerated simulators automatically from Chisel-based RTL design, and is the basis for simulator generation in FireSim.
> 
> MIDAS expands on the work of Strober that was originally developed for sample-based energy simulation. MIDAS was the basis for DESSERT (FPL2018) and includes FASED (FPGA2019), a generator of high-fidelity, reconfigurable LLC and DRAM memory-system models.

Seems like we could use the Strober sample-based energy estimator for quick PPA testing. Some of the host interface code may also be helpful.  It is written to interface with Chisel models / RocketChip so it may be challenging to use anything directly. Still, RocketChip+Firesim is similar to our goal of BlackParrot + BSG F1 infrastructure, so there may be some lessons learned that we can take advantage of.

**Comment by taylor-bsg** [comment]
I have either used or inspected a lot of this infrastructure already.
Generally Berkeley’s infrastructure is hopelessly entangled with the
Berkeley Rocket and Chisel infrastructure, bringing a huge amount of
useless code overhead with it. But in a few cases it is leaf code, pulling
in no other dependencies, and then it’s good.

- FASED: this seems like relatively modular leaf code and I have it already
flagged for use. It allows you to change the simulated timing of memory
systems in your FPGA.

- Firesim: a big pile of mud hopelessly entangled with 100 Berkeley repos.
Forget about it. Our F1 infrastructure is super solid, so no need to use
anything else.

- MIDAS: the idea is cool but I think a major project to get going, and I
don’t think we need it.

- Rocket host interface code. If you mean fesvr we should stay 1000 miles
away. Polling based interfaces leads to determinism and reproducibility
bugs leads to sadness.

- Sampling based energy interfaces. We had this in GreenDroid long before
the Strober work. You just need an interrupt that jumps to context switch
code that dumps out machine state.  Periodically dump it out and run on
your slow gate level RTL. We did this on the simulator but we can do it on
F1.
