### ISSUE TITLE
Use BaseJump STL

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#186]
https://github.com/black-parrot/pre-alpha-release/blob/19cd8defcda72d27de7595a615c4e3c49a01869c/bp_top/src/v/bp_clint.v#L77

**Comment by dpetrisko** [comment]
https://github.com/black-parrot/pre-alpha-release/blob/top_dev_feature_clintpdrework/bp_top/src/v/bp_clint.v
