### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#188]
https://github.com/black-parrot/pre-alpha-release/blob/19cd8defcda72d27de7595a615c4e3c49a01869c/bp_top/src/v/bp_clint.v#L148

If the code blindly assert valid, it is injecting packets into the network. Also, whether you yumi depends on whether you are able to send the outgoing packet.

**Comment by dpetrisko** [comment]
https://github.com/black-parrot/pre-alpha-release/blob/top_dev_feature_clintpdrework/bp_top/src/v/bp_clint.v
