### ISSUE TITLE
Generate refactor

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#190]
https://github.com/black-parrot/pre-alpha-release/blob/19cd8defcda72d27de7595a615c4e3c49a01869c/bp_top/src/v/bp_clint.v#L58

Prefer to have a single generate statement on the outside and group all per-core logic together into a factored module. This is more reusable.

**Comment by dpetrisko** [comment]
Fixed.

https://github.com/black-parrot/pre-alpha-release/blob/top_dev_feature_clintpdrework/bp_top/src/v/bp_clint.v
