### ISSUE TITLE
should contain clk if it is a clock.

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#191]
https://github.com/black-parrot/pre-alpha-release/blob/ec0b7b04d4e78d7bf6b83a2b28e7db690451f315/bp_top/src/v/bp_clint.v#L27

**Comment by dpetrisko** [comment]
rtc_clk_i?

**Comment by taylor-bsg** [comment]
Yep.

**Comment by dpetrisko** [comment]
Folding into #193
