### ISSUE TITLE
clk_i actually is used.

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#192]
https://github.com/black-parrot/pre-alpha-release/blob/ec0b7b04d4e78d7bf6b83a2b28e7db690451f315/bp_top/src/v/bp_clint.v#L90

**Comment by dpetrisko** [comment]
This is latest clint

https://github.com/black-parrot/pre-alpha-release/blob/top_dev_feature_clintpdrework/bp_top/src/v/bp_clint.v
