### ISSUE TITLE
Remove unnecessary assertion and parameter from be_regfile

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#248]
https://github.com/black-parrot/pre-alpha-release/blob/4522fbd2416940ef87a98bf0cc63bb3e8de4eda9/bp_be/src/v/bp_be_calculator/bp_be_regfile.v#L85

Seems like it is?

**Comment by dpetrisko** [comment]
good catch

**Comment by taylor-bsg** [comment]
Rename it bp_be_regfile_bypassing?

**Comment by dpetrisko** [comment]
Really, I should add the bypassing behavior to the RAM...

**Comment by dpetrisko** [comment]
Fixed in be_dev.  I left the name the same, because I would like (eventually) to parameterize bypassing support or no, reusing the rest of the module
