### ISSUE TITLE
bp_cce_pc.v

### ISSUE THREAD

**Issue by tommydcjung** [black-parrot/pre-alpha-release#25]
please read the section "Pull resets + enables into flop creation idioms and out of combi logic." on BSG style guide, and modify the state machine logic.

https://docs.google.com/document/d/1xA5XUzBtz_D6aSyIBQUwFk_kSUdckrfxa2uzGjMgmCU/edit#heading=h.b6iy34t1algh

**Comment by dpetrisko** [comment]
It might be helpful to link an example line number.

You can do this by going to the code, clicking on a line on the left side and copy-pasting the url

**Comment by tommydcjung** [comment]
https://github.com/black-parrot/pre-alpha-release/blob/dev/bp_me/src/v/cce/bp_cce_pc.v#L147

**Comment by dpetrisko** [comment]
I believe this is fixed in dev. @tommydcjung close if true
