### ISSUE TITLE
Poison the mem3 instruction on illegal CSR instructions

### ISSUE THREAD

**Issue by farzamgl** [black-parrot/pre-alpha-release#252]
The illegal CSR instructions do not poison the mem3 stage of the pipe right now, because their instr_v field is set in the decode stage. So I think a `mem3_trap_v_lo` should be added to this line in the calculator:
`exc_stage_n[3].poison_v        = exc_stage_r[2].poison_v | calc_status.mem3_miss_v; `

**Comment by taylor-bsg** [comment]
Anytime we find a bug there should be a test checked in with the fix.
