### ISSUE TITLE
[CLARITY] ucode

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#28]
Maybe either define what "ucode" means, or take it out? The term is not defined elsewhere in the source base.

https://github.com/black-parrot/pre-alpha-release/blob/3e97c60fe6b7129871d98436f8cfb147c8695dc0/bp_be/src/include/bp_be_ucode_defines.vh#L1

**Comment by dpetrisko** [comment]
Is there a better name for pipeline control signals than microcode?

**Comment by taylor-bsg** [comment]
bp_be_ctl_defines ?

microcode usually means that you have a sequencer (i.e. like the CCE), so at least in my frame of reference this is not really microcode

**Comment by dpetrisko** [comment]
Fixed in latest dev
