### ISSUE TITLE
[PHYSICAL_DESIGN] Label generate statements.

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#36]
A few of the generate statements do not have labels on their begins, which will show up with synthesis dependent keywords. See the BSG SystemVerilog coding guidelines.

https://github.com/black-parrot/pre-alpha-release/blob/3e97c60fe6b7129871d98436f8cfb147c8695dc0/bp_fe/src/v/bp_fe_icache.v#L1

**Comment by spikemar** [comment]
@tommydcjung I think this issue also exists in some of the dcache code.
