### ISSUE TITLE
[CLARITY] Redundant combinational block lines

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#38]
For combinational blocks like this, set the default values for all variables at the top, and then modify the defaults in the if else if else clause. You don't need to have a final clause that sets defaults, since you already did it at the top.

https://github.com/black-parrot/pre-alpha-release/blob/62d31b3774b875e2c4fd5c64e79231780b77c2b6/bp_me/src/v/cce/bp_cce_pc.v#L74

**Comment by muwyse** [comment]
This has mostly already been resolved, and is fully resolved with bp_me-cfg branch that will merge soon.
