### ISSUE TITLE
[CLARITY] Track down odd synthesis bug.

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#39]
https://github.com/black-parrot/pre-alpha-release/blob/3e97c60fe6b7129871d98436f8cfb147c8695dc0/bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v#L188

**Comment by dpetrisko** [comment]
Fixed in latest dev

**Comment by dpetrisko** [comment]
Fixed.  Had to do with mismatched parameterized struct widths
