### ISSUE TITLE
[PHYSICAL_DESIGN] Synthesis issue

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#40]
Tack down and fix this synthesis issue.

https://github.com/black-parrot/pre-alpha-release/blob/3e97c60fe6b7129871d98436f8cfb147c8695dc0/bp_be/src/v/bp_be_mmu/bp_be_mmu_top.v#L216

**Comment by dpetrisko** [comment]
Fixed in dev
