### ISSUE TITLE
[CLARITY]: Factor for clarity

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#42]
This code gets repeated multiple times, and should be factored into an expression for readability.
Additionally, a comment explaining the calculation that is going on would be helpful.

                                              & ~|exc_stage_r[i] 
                                              & calc_stage_r[i].decode.irf_w_v;

https://github.com/black-parrot/pre-alpha-release/blob/3e97c60fe6b7129871d98436f8cfb147c8695dc0/bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v#L502

**Comment by dpetrisko** [comment]
Live in dev: Simplified to only check for poison_v (which is better for critical path, as well).
