### ISSUE TITLE
[CLARITY]

### ISSUE THREAD

**Issue by taylor-bsg** [black-parrot/pre-alpha-release#43]
This code will be much easier to check for bugs and to understand if you sort the roll_v updates together, and the poison_v updates together.

https://github.com/black-parrot/pre-alpha-release/blob/3e97c60fe6b7129871d98436f8cfb147c8695dc0/bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v#L550

**Comment by dpetrisko** [comment]
Fixed in dev
