### ISSUE TITLE
[PHYSICAL_DESIGN] Synth rams should not be used

### ISSUE THREAD

**Issue by black-parrot** [black-parrot/pre-alpha-release#44]
You should use the version of the ram that does not end in _synth; those are for internal BaseJump STL use, and using them prevents us from hardening the SRAM. The non-synth versions will either end up instantiating the _synth versions underneath, or hardened SRAMs.

https://github.com/black-parrot/pre-alpha-release/blob/3e97c60fe6b7129871d98436f8cfb147c8695dc0/bp_be/src/v/bp_be_mmu/bp_be_tlb/bp_be_tlb.v#L97

**Comment by farzamgl** [comment]
Fixed in a commit to "be_dev" along with some other changes. Will update on the next merge.
