### ISSUE TITLE
[CLARITY] Code replication on cam

### ISSUE THREAD

**Issue by black-parrot** [black-parrot/pre-alpha-release#45]
We have a cam in bsg_ip_cores (BaseJump STL) that seems very similar. Is there anything unique about this one? Otherwise we should use the BaseJump STL one. Or if they are different, what is the change and how should we improve BaseJump STL to accommodate it?

https://github.com/black-parrot/pre-alpha-release/blob/3e97c60fe6b7129871d98436f8cfb147c8695dc0/bp_be/src/v/bp_be_mmu/bp_be_tlb/bp_tlb_cam.v#L2

**Comment by farzamgl** [comment]
"bp_tlb_cam" also outputs the first empty entry which makes the TLB write easier when there are still some empty locations.

**Comment by taylor-bsg** [comment]
Okay great. Can you reconcile them and commit to bsg_ip_cores? It looks like bsg_cam_1r1w allows you to have multiple entries in the CAM, and has a few improved coding practices, but the finding empty entry could also be useful. Maybe have a parameter find_empty_p that says whether it should find the empty entries, and it can assert empty_v_o and skip the priority encoder if it is set.

**Comment by farzamgl** [comment]
Should I modify the current module or create a new one? Because it might break the design of the people that are using the current version in bsg_ip_cores.

**Comment by taylor-bsg** [comment]
Thanks Farzam -- not to worry, nobody is using that module yet. Zhara from BU wrote it, probably to use in the FE TLB. =)
