### ISSUE TITLE
[CLARITY]: Pseudo LRU module --> BaseJump STL?

### ISSUE THREAD

**Issue by black-parrot** [black-parrot/pre-alpha-release#47]
This seems like a neat module. Perhaps we should have it in BaseJump STL? Does it work, or does it have outstanding issues? Also, should it be folded into the data cache as well?

https://github.com/black-parrot/pre-alpha-release/blob/master/bp_be/src/v/bp_be_mmu/bp_be_dcache/bp_be_dcache_lru_decode.v

https://github.com/black-parrot/pre-alpha-release/blob/3e97c60fe6b7129871d98436f8cfb147c8695dc0/bp_be/src/v/bp_be_mmu/bp_be_tlb/bp_plru.v#L2

**Comment by tommydcjung** [comment]
there is encode and decode part. By looking at its ports, I'm not sure if it does the same thing as in dcache_lru modules. Also this should be a combinational logic.

**Comment by farzamgl** [comment]
This is basically the encode, decode and the LRU register in a single module. I suppose we can separate them if needed and try to use it in the d-cache as well.

**Comment by taylor-bsg** [comment]
Farzam's code handles the general case of n-way though, or is that not true?

**Comment by farzamgl** [comment]
Yes, it's parameterized for N way.

**Comment by taylor-bsg** [comment]
Cool. Maybe refine the interface with Tommy and see if you can create something that would generalize well for BaseJump STL and work in these two use cases.
