### ISSUE TITLE
[PPA_MEDIUM] Optimize FE/BE for non-64 bit virtual addresses

### ISSUE THREAD

**Issue by black-parrot** [black-parrot/pre-alpha-release#52]
Virtual addresses are not 64-bit, so there are opportunities to optimize away bits. However, the semantics of overflow/underflow are a little tricky, and we need to know where in the processor we need the full (illegal) 64-bit address.

**Comment by dpetrisko** [comment]
Adding to this, reducing internal physical address to 39 bits, while supporting 56 bit physical address entries in the page table.

**Comment by dpetrisko** [comment]
Done in dev. I think all of the edge cases are accounted for, but this is something that either needs formal or google's randomized page table testing, most likely
