### ISSUE TITLE
Vtag Ptag Calculation

### ISSUE THREAD

**Issue by spikemar** [black-parrot/pre-alpha-release#57]
https://github.com/black-parrot/pre-alpha-release/blob/71a28a51c186fc3d997c91f37139747cc48f2ead/bp_be/src/v/bp_be_mmu/bp_be_mmu_top.v#L110

If this is going to be changed such that it is v/p tag = v/p addr - offset_gp (similar to the way ptag is calculated in dcache), should we just assign v/p tag in bp_common instead of calculating it everywhere? Seems kinda redundant.

**Comment by dpetrisko** [comment]
I agree, if we're only supporting sv39.  But we may want to have a mode with VM disabled, for example, in which case vtag / ptag are not _gp
