### ISSUE TITLE
[CLARITY] _li and _lo should be used for inputs and outputs of child modules, not _o or _i

### ISSUE THREAD

**Issue by black-parrot** [black-parrot/pre-alpha-release#94]
See title; here is an example:

https://github.com/black-parrot/pre-alpha-release/blob/8a9000eb112538204d5bfb27bff71501b61558f1/bp_me/src/v/cce/bp_cce.v#L181

**Comment by taylor-bsg** [comment]
@muwyse Mark this has been outstanding for a while, can you please go ahead and fix?

**Comment by muwyse** [comment]
I'll bring it in with next set of changes
